on: 
 pull_request:
    branches: [ master ]
    types: [closed] 
jobs:
  repo-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/nodejs-prof/backend.git"
        SOURCE_BRANCH: "master"
        GITHUB_TOKEN: ${{ secrets.GIT_OAUTH_TOKEN }}
        DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
        DESTINATION_BRANCH: "master"
      with:
        global: true
        token: $GITHUB_TOKEN
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
